- id: tenet
  name: tenet
  description: Lint the staged changes against tenets.yml
  entry: tenet
  language: golang
  pass_filenames: false
  stages: [pre-commit]

- id: tenet-commit-msg
  name: tenet commit message
  description: Lint the commit message against tenets.yml
  entry: tenet --commit-msg
  language: golang
  pass_filenames: true
  stages: [commit-msg]
